In [11]:
import pandas as pd 
import yfinance as yf
df = yf.download('2454.TW',start = '2025-01-01',end = '2025-03-31') # 2454.TW的股價資料
df
# df['Close']['2454.TW']
# for i in range(len(df['Close']['2454.TW'])):
#     print('從2025年起，第',len(df['Close']['2454.TW'])-i,'個交易日的收盤價格為：',df['Close']['2454.TW'][i])

[*********************100%***********************]  1 of 1 completed

Price        Close    High     Low    Open    Volume
Ticker     2454.TW 2454.TW 2454.TW 2454.TW   2454.TW
Date
2025-01-02  1350.0  1400.0  1335.0  1395.0   6820305
2025-01-03  1365.0  1370.0  1335.0  1365.0   5752498
2025-01-06  1425.0  1425.0  1390.0  1390.0   6907233
2025-01-07  1490.0  1500.0  1415.0  1445.0  12307998
2025-01-08  1470.0  1500.0  1460.0  1500.0  10805038
2025-01-09  1440.0  1480.0  1440.0  1470.0   7021298
2025-01-10  1465.0  1495.0  1445.0  1460.0   7157266
2025-01-13  1390.0  1460.0  1385.0  1435.0   9742772
2025-01-14  1400.0  1415.0  1380.0  1385.0   5279672
2025-01-15  1420.0  1445.0  1390.0  1390.0   6417175
2025-01-16  1460.0  1470.0  1430.0  1450.0   7314623
2025-01-17  1430.0  1455.0  1420.0  1450.0   5488719
2025-01-20  1445.0  1455.0  1425.0  1425.0   3956489
2025-01-21  1465.0  1475.0  1435.0  1440.0   4428280
2025-01-22  1465.0  1495.0  1465.0  1480.0   6502859
2025-02-03  1500.0  1525.0  1415.0  1420.0  18533177
2025-02-04  1490.0  1530.0  1480.0  1510.0   8166768
2025-02-05  1525.0  1530.0  1490.0  1505.0   9064753
2025-02-06  1525.0  1570.0  1520.0  1530.0   9371366
2025-02-07  1525.0  1530.0  1505.0  1525.0   6741142
2025-02-10  1480.0  1510.0  1475.0  1505.0   8922872
2025-02-11  1510.0  1530.0  1490.0  1490.0   8486272
2025-02-12  1485.0  1540.0  1480.0  1530.0   7865557
2025-02-13  1520.0  1520.0  1485.0  1495.0   4576098
2025-02-14  1505.0  1535.0  1505.0  1515.0   4726126
2025-02-17  1545.0  1545.0  1510.0  1515.0   7603778
2025-02-18  1535.0  1550.0  1520.0  1550.0   5362376
2025-02-19  1540.0  1545.0  1525.0  1535.0   4447177
2025-02-20  1500.0  1545.0  1500.0  1545.0   6855773
2025-02-21  1510.0  1525.0  1490.0  1500.0   5655119
2025-02-24  1545.0  1545.0  1495.0  1500.0   6371982
2025-02-25  1550.0  1560.0  1510.0  1525.0   7905273
2025-02-26  1560.0  1575.0  1525.0  1555.0   7032006
2025-02-27  1515.0  1575.0  1515.0  1555.0  10335277
2025-03-03  1470.0  1495.0  1465.0  1490.0  10588492
2025-03-04  1505.0  1510.0  1435.0  1435.0   7871467
2025-03-05  1505.0  1530.0  1490.0  1505.0   6356979
2025-03-06  1495.0  1510.0  1485.0  1505.0   3089136
2025-03-07  1465.0  1485.0  1450.0  1475.0   5464123
2025-03-10  1395.0  1460.0  1395.0  1450.0   9828231
2025-03-11  1385.0  1390.0  1320.0  1320.0  10078176
2025-03-12  1410.0  1425.0  1375.0  1375.0   7914116
2025-03-13  1390.0  1440.0  1390.0  1430.0   6948447
2025-03-14  1400.0  1430.0  1390.0  1400.0   7153832
2025-03-17  1425.0  1440.0  1415.0  1415.0   4878893
2025-03-18  1475.0  1500.0  1445.0  1450.0  10224305
2025-03-19  1465.0  1515.0  1460.0  1500.0   7855359
2025-03-20  1485.0  1500.0  1465.0  1495.0   6419295
2025-03-21  1480.0  1500.0  1475.0  1495.0   4597519
2025-03-24  1480.0  1505.0  1480.0  1500.0   3925730
2025-03-25  1525.0  1540.0  1505.0  1505.0   7987673
2025-03-26  1515.0  1540.0  1515.0  1535.0   3637846
2025-03-27  1485.0  1510.0  1480.0  1500.0   4779867
2025-03-28  1465.0  1495.0  1455.0  1470.0   4529681